import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getShareSnapshot } from "@/lib/share-store";
import styles from "./verify.module.css";

type Params = { id: string };

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `Verified Share ${id} | Consist`,
    description: "Verification page for a Consist shared result.",
    robots: { index: false, follow: false },
  };
}

export default async function VerifySharePage({ params }: { params: Promise<Params> }) {
  const { id } = await params;
  const snapshot = await getShareSnapshot(id);
  if (!snapshot) notFound();

  const activeDays = snapshot.days.length;
  const greenDays = snapshot.days.filter((d) => d.variant !== "neg").length;
  const redDays = snapshot.days.filter((d) => d.variant === "neg").length;
  const generatedAt = new Date(snapshot.createdAt);
  const issuedAt = Number.isNaN(generatedAt.getTime())
    ? "Unknown date"
    : generatedAt.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });

  return (
    <main className={styles.page}>
      <section className={styles.card}>
        <div className={styles.badge}>Consist Verified</div>
        <h1>Share is valid</h1>
        <p className={styles.sub}>This result was generated by Consist and matches stored snapshot data.</p>

        <div className={styles.grid}>
          <article className={styles.item}>
            <span>Discipline score</span>
            <strong>{snapshot.score}%</strong>
          </article>
          <article className={styles.item}>
            <span>Green streak</span>
            <strong>{snapshot.greenStreak}</strong>
          </article>
          <article className={styles.item}>
            <span>Red streak</span>
            <strong>{snapshot.redStreak}</strong>
          </article>
          <article className={styles.item}>
            <span>Tracked days</span>
            <strong>{activeDays}</strong>
          </article>
          <article className={styles.item}>
            <span>Green / Red days</span>
            <strong>
              {greenDays} / {redDays}
            </strong>
          </article>
          <article className={styles.item}>
            <span>Issued at</span>
            <strong>{issuedAt}</strong>
          </article>
        </div>

        <div className={styles.actions}>
          <Link href={`/s/${snapshot.id}`}>Open shared card</Link>
          <Link href="/login" className={styles.primary}>
            Build your own
          </Link>
        </div>
      </section>
    </main>
  );
}
